<a href="https://colab.research.google.com/github/lathamithu/DSCWOW_SafeStorage-Strengthen_Productivity_using_ML_IOT/blob/main/SAFE_STORAGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(color_codes=True)

In [ ]:
data=pd.read_csv("/content/birac (1).csv")

In [ ]:
data.head()

Unnamed: 0 STATE MONTH HUMIDITY TEMPERATURE MOISTURE SAFE
0           0    TN   JAN       75          25        8  395
1           1    TN   JAN       77          25       14  143
2           2    TN   JAN       76          25       29   19
3           3    TN   JAN       72          25       20   64
4           4    TN   JAN       73          25       15   64

In [ ]:
data['SAFE'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
1471    False
1472    False
1473    False
1474    False
1475    False
Name: SAFE, Length: 1476, dtype: bool

In [ ]:
data.loc[data["SAFE"]=="NIL"]=0

In [ ]:
data["SAFE"]=pd.to_numeric(data["SAFE"])

In [ ]:
data.head()

Unnamed: 0 STATE MONTH HUMIDITY TEMPERATURE MOISTURE  SAFE
0           0    TN   JAN       75          25        8   395
1           1    TN   JAN       77          25       14   143
2           2    TN   JAN       76          25       29    19
3           3    TN   JAN       72          25       20    64
4           4    TN   JAN       73          25       15    64

In [ ]:
from sklearn.model_selection import train_test_split
feature_col_names=['HUMIDITY','TEMPERATURE','MOISTURE']
predicted_class_name=['SAFE']
x=data[feature_col_names].values
y=data[predicted_class_name].values
split_test_size=0.30
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=split_test_size,random_state=1)

In [ ]:
#To check the correctness of splitting
trainval=(1.0 * len(x_train)/(1.0 * len(data.index)))
testval=(len(x_test))/(len(data.index))
print(trainval)
print(testval)
print('{0:0.2f}% in training set '.format((trainval)*100))
print('{0:0.2f}% in testing set '.format((testval)*100))

0.6998644986449865
0.30013550135501355
69.99% in training set 
30.01% in testing set 


# **DECISION TREE**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,
                              min_samples_leaf=5)
clf_gini.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [ ]:
y_pred = clf_gini.predict(x_test)
y_pred

array([  0,  64, 143,   4,   0,  64,   0,   0,   4,   4,   4,   0, 349,
         4,   0, 395,  64,   0, 365,   0,   0,  64,  19,  19,  64, 143,
       464,  64, 512,  19,   4,   0,   0,  64,   0,   0,   0,  19,   0,
         0,   0,   0,  19, 243, 143, 365, 365,   0,   0, 273,  19,   0,
         0,   4,   0,   0, 319,   4,   4,   0,   4,   4,   0,  64,  64,
        19,  19, 349,   0,   4,   0,   0,   4,  64,   0,   0,   4, 349,
         4,   0, 464,  64,   0,   0,   4, 319,   0,   0,   4,   4,  19,
       319,  64,  64,   0,   0,  19,  19, 512,   4, 395,  64,   4, 243,
         0,  19,   4,  19, 319,  64, 365,   4,   4,   0,   4,   0,   0,
       243,  64, 349,  64,   0,  19, 319, 143,   0,  19,  64,   0, 365,
       319,  64,  19, 273,  64, 583,   0,  19,   0,   0, 349,   0, 243,
       243, 464,   0,   0,   0, 464,   0, 243,   4,   0,   4,   4,   0,
       464, 273,   0,   4,   0,   0,   0,  64, 273, 349, 143,  64,   0,
       365,   0,  64,  64,   0,   0, 143,  64, 583,  19,  64,   

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print ("Accuracy is "), accuracy_score(y_test,y_pred)*100

Accuracy is 


(None, 100.0)

In [ ]:
clf_gini.predict([[70,20,10]])

array([349])

In [ ]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy",random_state = 100,
 min_samples_leaf=5)
clf_entropy.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [ ]:
y_pred_en = clf_entropy.predict(x_test)
y_pred_en

array([  0,  64, 143,   4,   0,  64,   0,   0,   4,   4,   4,   0, 349,
         4,   0, 395,  64,   0, 365,   0,   0,  64,  19,  19,  64, 143,
       464,  64, 512,  19,   4,   0,   0,  64,   0,   0,   0,  19,   0,
         0,   0,   0,  19, 243, 143, 365, 365,   0,   0, 273,  19,   0,
         0,   4,   0,   0, 319,   4,   4,   0,   4,   4,   0,  64,  64,
        19,  19, 349,   0,   4,   0,   0,   4,  64,   0,   0,   4, 349,
         4,   0, 464,  64,   0,   0,   4, 319,   0,   0,   4,   4,  19,
       319,  64,  64,   0,   0,  19,  19, 512,   4, 395,  64,   4, 243,
         0,  19,   4,  19, 319,  64, 365,   4,   4,   0,   4,   0,   0,
       243,  64, 349,  64,   0,  19, 319, 143,   0,  19,  64,   0, 365,
       319,  64,  19, 273,  64, 583,   0,  19,   0,   0, 349,   0, 243,
       243, 464,   0,   0,   0, 464,   0, 243,   4,   0,   4,   4,   0,
       464, 273,   0,   4,   0,   0,   0,  64, 273, 349, 143,  64,   0,
       365,   0,  64,  64,   0,   0, 143,  64, 583,  19,  64,   

In [ ]:
print ("Accuracy is "), accuracy_score(y_test,y_pred_en)*100

Accuracy is 


(None, 100.0)

# **RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [ ]:
rfc.fit(x_train,y_train.ravel())

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred_rfc = rfc.predict(x_test)
y_pred_rfc

array([  0,  64, 143,   4,   0,  64,   0,   0,   4,   4,   4,   0, 349,
         4,   0, 395,  64,   0, 365,   0,   0,  64,  19,  19,  64, 273,
       464,  64, 512,  19,   4,   0,   0,  64,   0,   0,   0,  19,   0,
         0,   0,   0,  19, 243, 143, 365, 319,   0,   0, 273,  19,   0,
         0,   4,   0,   0, 365,   4,   4,   0,   4,   4,   0,  64,  64,
        19,  19, 349,   0,   4,   0,   0,   4,  64,   0,   0,   4, 349,
         4,   0, 243,  64,   0,   0,   4, 349,   0,   0,   4,   4,  19,
       319,  64,  64,   0,   0,  19,  19, 512,   4, 395,  64,   4, 243,
         0,  19,   4,  19,  64,  64, 365,   4,   4,   0,   4,   0,   0,
       143,  64, 349,  64,   0,  19, 319, 319,   0,  19,  64,   0, 365,
       243,  64,  19, 243,  64, 512,   0,  19,   0,   0, 365,   0, 243,
       243, 464,   0,   0,   0, 365,   0, 349,   4,   0,   4,   4,   0,
       464, 143,   0,   4,   0,   0,   0,  64, 319, 349, 273,  64,   0,
       365,   0,  64,  64,   0,   0, 143,  64, 512,  19,  64,   

In [ ]:
print ("Accuracy is "), accuracy_score(y_test,y_pred_rfc)*100

Accuracy is 


(None, 89.1647855530474)

# **KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train,y_train.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred_knn = knn.predict(x_test)
y_pred_knn

array([  0,  64,  64,   4,   0,  64,   0,   0,   4,   4,   4,   0, 349,
         4,   0, 395,  64,   0, 349,   0,   0,  64,  19,  19,  64,  64,
       464,  64, 512,  19,   4,   0,   0,  64,   0,   0,   0,  19,   0,
         0,   0,   0,  19, 143,  64, 319, 319,   0,   0, 273,  19,   0,
         0,   4,   0,   0, 349,   4,   4,   0,   4,   4,   0,  64,  64,
        19,  19, 349,   0,  19,   0,   0,   4,  64,   0,   0,   4, 349,
         4,   0, 464,  64,   0,   0,  19, 349,   0,   0,   4,   4,  19,
       319,  64,  64,   0,   0,  19,  19, 464,   4, 395,  64,   4, 243,
         0,  19,   4,  19, 319,  64, 365,   4,   4,   0,   4,   0,   0,
       319,  64, 365,  64,   0,  19, 319, 143,   0,  64,  64,   0, 365,
       273,  64,  19, 243,  64, 512,   0,  19,   0,   0, 319,   0,  64,
        64, 395,   0,   0,   0, 464,   0, 243,   4,   0,   4,   4,   0,
       464, 143,   0,   4,   0,   0,   0,  64, 243, 319, 243,  64,   0,
       319,   4,  64,  64,   0,   0, 143,  64, 512,  19,  64,   

In [ ]:
print ("Accuracy is "), accuracy_score(y_test,y_pred_knn)*100

Accuracy is 


(None, 81.941309255079)

# **NAIVE BAYES**

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
classifier=GaussianNB()
classifier.fit(x_train,y_train.ravel())

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred_nb = classifier.predict(x_test)
y_pred_nb

array([  0,  64, 143,   4,   0,  64,   0,   0,   4,   4,   0,   0, 349,
         4,   0, 395,  64,   0, 365,   0,   0,  64,  19,  19,  64, 143,
       464,  64, 512,  19,   4,   0,   0,  64,   0,   0,   0,  19,   0,
         0,   0,   0,  19, 243, 143, 365, 365,   0,   0, 273,  19,   0,
         0,   4,   0,   0, 319,   4,   4,   0,   4,   4,   0,  64,  64,
        19,  19, 349,   0,   4,   0,   0,   4,  64,   0,   0,   4, 349,
         4,   0, 464,  64,   0,   0,   4, 319,   0,   0,   4,   4,  19,
       319,  64,  64,   0,   0,  19,  19, 512,   4, 395,  64,   4, 243,
         0,  19,   4,  19, 319,  64, 365,   4,   4,   0,   4,   0,   0,
       243,  64, 349,  64,   0,  19, 319, 143,   0,  19,  64,   0, 365,
       319,  64,  19, 273,  64, 583,   0,  19,   0,   0, 349,   0, 243,
       243, 464,   0,   0,   0, 464,   0, 243,   4,   0,   0,   4,   0,
       464, 273,   0,   4,   0,   0,   0,  64, 273, 349, 143,  64,   0,
       365,   0,  64,  64,   0,   0, 143,  64, 512,  19,  64,   

In [ ]:
print ("Accuracy is "), accuracy_score(y_test,y_pred_nb)*100

Accuracy is 


(None, 98.1941309255079)